services:
  postgres:
    image: postgres:16-alpine
    container_name: mahaveer_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: mahaveer_db
      POSTGRES_USER: mahaveer_user
      POSTGRES_PASSWORD: mahaveer_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mahaveer_user -d mahaveer_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local
